# Generated by Django 3.2.6 on 2021-08-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=225, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video_id', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Movie Video',
                'verbose_name_plural': 'Table Show Videos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FastEditVideoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Editable Video',
                'verbose_name_plural': 'Fast Edit Videos',
                'ordering': ['title'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('video.video',),
        ),
        migrations.CreateModel(
            name='PublishedVideoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Publish Video',
                'verbose_name_plural': 'Published Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('video.video',),
        ),
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Movie Video',
                'verbose_name_plural': 'Basic Video Title Show',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('video.video',),
        ),
    ]
