# Generated by Django 3.2.6 on 2021-08-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0002_remove_playlist_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="playlist",
            name="published_timestamp",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="state",
            field=models.CharField(
                choices=[
                    ("PU", "PUBLISH"),
                    ("DR", "DRAFT"),
                    ("UN", "Unlisted"),
                    ("PR", "Private"),
                ],
                default="DR",
                max_length=2,
            ),
        ),
    ]
